// <auto-generated />
namespace CssTemplatesForFree.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class addedcsstempaltetbl : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedcsstempaltetbl));
        
        string IMigrationMetadata.Id
        {
            get { return "201410021428194_addedcsstempaltetbl"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
